import Head from 'next/head'
import Image from 'next/image'
import Callforpapers from './Callforpapers'
import Committie from './Committie'
import Conference from './conference'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Callforpapers />
 <Committie />
 <Conference />
    </div>
  )
}
